# -*- coding: utf-8 -*-
"""homework3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IErwj4vK0Sn9EAA2zExc4s1StNYXBtvF
"""

import kagglehub
import os
import csv

#Download dataset
path = kagglehub.dataset_download("uciml/sms-spam-collection-dataset")

print(path)
print(os.listdir(path))

def load_spam_dataset(file_path):
    dataset = []

    with open(file_path, "r", encoding="latin-1") as file:
        reader = csv.reader(file)

        # skip header
        next(reader)

        for row in reader:
            label_text = row[0]
            text = row[1]

            if label_text == "spam":
                label = 1
            else:
                label = -1

            dataset.append((text, label))

    return dataset

file_path = path + "/spam.csv"

dataset = load_spam_dataset(file_path)

print("Dataset size:", len(dataset))
print(dataset[:5])

print(type(dataset))
print(len(dataset))
print(dataset[0])

import random

#Train-test split

random.seed(42)
random.shuffle(dataset)

split_index = int(len(dataset) * 0.8)

train_data = dataset[:split_index]
test_data = dataset[split_index:]

print("Training size:", len(train_data))
print("Test size:", len(test_data))

# Tokenization

def tokenize(text):
    return text.lower().split()

# Build vocabulary

def build_vocab(dataset):
    vocab = set()

    for text, label in dataset:
        words = tokenize(text)
        vocab.update(words)

    return {word: i for i, word in enumerate(vocab)}


vocab = build_vocab(train_data)

print("Vocabulary size:", len(vocab))

# Vectorize text

def vectorize(text):
    vector = [0] * len(vocab)

    words = tokenize(text)

    for word in words:
        if word in vocab:
            index = vocab[word]
            vector[index] = 1

    return vector


print(vectorize("free money now")[:20])

# Initialize model

w = [0] * len(vocab)
b = 0

# Predict

def predict(x):
    global b

    score = 0

    for i in range(len(x)):
        score += w[i] * x[i]

    score += b

    if score > 0:
        return 1      # spam
    else:
        return -1     # ham / normal

# Update

def update(x, y):
    global w, b

    y_pred = predict(x)

    if y_pred != y:
        for i in range(len(w)):
            w[i] = w[i] + y * x[i]

        b = b + y

# Training

epochs = 10

for epoch in range(epochs):
    errors = 0

    for text, label in train_data:
        x = vectorize(text)
        old_prediction = predict(x)

        if old_prediction != label:
            errors += 1

        update(x, label)

    print("Epoch:", epoch + 1, "Errors:", errors)

# Testing

gold_labels = []
predictions = []

for text, label in test_data:
    x = vectorize(text)
    pred = predict(x)

    gold_labels.append(label)
    predictions.append(pred)

print("Number of predictions:", len(predictions))
print("Number of gold labels:", len(gold_labels))

# Evaluation

def precision(gold_labels, predictions):
    true_positive = 0
    false_positive = 0

    for gold, pred in zip(gold_labels, predictions):
        if pred == 1 and gold == 1:
            true_positive += 1
        elif pred == 1 and gold == -1:
            false_positive += 1

    if true_positive + false_positive == 0:
        return 0

    return true_positive / (true_positive + false_positive)


def recall(gold_labels, predictions):
    true_positive = 0
    false_negative = 0

    for gold, pred in zip(gold_labels, predictions):
        if pred == 1 and gold == 1:
            true_positive += 1
        elif pred == -1 and gold == 1:
            false_negative += 1

    if true_positive + false_negative == 0:
        return 0

    return true_positive / (true_positive + false_negative)


def f1_score(gold_labels, predictions):
    p = precision(gold_labels, predictions)
    r = recall(gold_labels, predictions)

    if p + r == 0:
        return 0

    return 2 * p * r / (p + r)


print("Precision:", precision(gold_labels, predictions))
print("Recall:", recall(gold_labels, predictions))
print("F1 Score:", f1_score(gold_labels, predictions))

# Manual tests

tests = [
    "free money now",
    "call me later",
    "win a free prize now",
    "let's meet tomorrow",
    "urgent claim your reward"
]

for t in tests:
    x = vectorize(t)
    print(t, "->", predict(x))