# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Ly-pFdmUWqgV38F42mIJB4Xs3-48Z7H
"""

class EvaluationMetrics:

    def __init__(self, y_true, y_pred):

        if len(y_true) != len(y_pred):
            raise ValueError("y_true and y_pred must have the same length.")
# something wrong in input data
        self.y_true = y_true
        self.y_pred = y_pred

    def unique_labels(self):

        labels = []
        for label in self.y_true:
            if label not in labels:
                labels.append(label)
        for label in self.y_pred:
            if label not in labels:
                labels.append(label)

        try:
            return sorted(labels)
        except TypeError:
            # If labels are mixed types and cannot be sorted, return insertion order
            return labels
        """
        for example labels = [1, "cat", 3]
        do not know how to sort it
        so return old labels
        """

    def confusion_matrix_binary(self, positive_label=1):
        """
        positive_label is treated as the positive class.
        Everything else is treated as negative.
        """
        tp = 0
        fp = 0
        fn = 0
        tn = 0

        for true_label, pred_label in zip(self.y_true, self.y_pred):
            if true_label == positive_label and pred_label == positive_label:
                tp += 1
            elif true_label != positive_label and pred_label == positive_label:
                fp += 1
            elif true_label == positive_label and pred_label != positive_label:
                fn += 1
            else:
                tn += 1

        return tp, fp, fn, tn

    def accuracy(self):
        """
            number of correct predictions / total number of predictions
        """
        total = len(self.y_true)
        if total == 0:
            return 0.0

        correct = 0
        for true_label, pred_label in zip(self.y_true, self.y_pred):
            if true_label == pred_label:
                correct += 1

        return correct / total

    def precision_binary(self, positive_label=1):
        """
        TP / (TP + FP)

        If denominator is 0, return 0.0
        """
        tp, fp, fn, tn = self.confusion_matrix_binary(positive_label)

        if tp + fp == 0:
            return 0.0

        return tp / (tp + fp)

    def recall_binary(self, positive_label=1):
        """
        TP / (TP + FN)

        If denominator is 0, return 0.0
        """
        tp, fp, fn, tn = self.confusion_matrix_binary(positive_label)

        if tp + fn == 0:
            return 0.0

        return tp / (tp + fn)

    def f1_binary(self, positive_label=1):
        """
        2 * precision * recall / (precision + recall)

        If denominator is 0, return 0.0
        """
        precision = self.precision_binary(positive_label)
        recall = self.recall_binary(positive_label)

        if precision + recall == 0:
            return 0.0

        return 2 * precision * recall / (precision + recall)

    def confusion_matrix_multiclass(self):
        #matrix[true_label][pred_label] = count

        labels = self.unique_labels()
        matrix = {}

        for true_label in labels:
            matrix[true_label] = {}
            for pred_label in labels:
                matrix[true_label][pred_label] = 0

        for true_label, pred_label in zip(self.y_true, self.y_pred):
            matrix[true_label][pred_label] += 1

        return matrix

    def precision_for_label(self, label):
        """
        TP / (TP + FP)

        If denominator is 0, return 0.0
        """
        tp = 0
        fp = 0

        for true_label, pred_label in zip(self.y_true, self.y_pred):
            if pred_label == label and true_label == label:
                tp += 1
            elif pred_label == label and true_label != label:
                fp += 1

        if tp + fp == 0:
            return 0.0

        return tp / (tp + fp)

    def recall_for_label(self, label):
        tp = 0
        fn = 0

        for true_label, pred_label in zip(self.y_true, self.y_pred):
            if true_label == label and pred_label == label:
                tp += 1
            elif true_label == label and pred_label != label:
                fn += 1

        if tp + fn == 0:
            return 0.0

        return tp / (tp + fn)

    def f1_for_label(self, label):
        precision = self.precision_for_label(label)
        recall = self.recall_for_label(label)

        if precision + recall == 0:
            return 0.0

        return 2 * precision * recall / (precision + recall)

    def macro_precision(self):
        labels = self.unique_labels()
        if len(labels) == 0:
            return 0.0

        total = 0.0
        for label in labels:
            total += self.precision_for_label(label)

        return total / len(labels)

    def macro_recall(self):
        """
        Macro-averaged recall:
        average recall across all labels.
        """
        labels = self.unique_labels()
        if len(labels) == 0:
            return 0.0

        total = 0.0
        for label in labels:
            total += self.recall_for_label(label)

        return total / len(labels)

    def macro_f1(self):
        labels = self.unique_labels()
        if len(labels) == 0:
            return 0.0

        total = 0.0
        for label in labels:
            total += self.f1_for_label(label)

        return total / len(labels)

    def evaluate_binary(self, positive_label=1):

        tp, fp, fn, tn = self.confusion_matrix_binary(positive_label)

        return {
            "TP": tp,
            "FP": fp,
            "FN": fn,
            "TN": tn,
            "accuracy": self.accuracy(),
            "precision": self.precision_binary(positive_label),
            "recall": self.recall_binary(positive_label),
            "f1": self.f1_binary(positive_label),
        }

    def evaluate_multiclass(self):
        labels = self.unique_labels()
        per_label = {}

        for label in labels:
            per_label[label] = {
                "precision": self.precision_for_label(label),
                "recall": self.recall_for_label(label),
                "f1": self.f1_for_label(label),
            }

        return {
            "labels": labels,
            "confusion_matrix": self.confusion_matrix_multiclass(),
            "accuracy": self.accuracy(),
            "per_label": per_label,
            "macro_precision": self.macro_precision(),
            "macro_recall": self.macro_recall(),
            "macro_f1": self.macro_f1(),
        }


def run_tests():

    print("===== BINARY TESTS =====")

    # Test 1: normal binary case
    y_true = [1, 0, 1, 1, 0, 0, 1, 0]
    y_pred = [1, 1, 1, 0, 0, 0, 1, 0]

    evaluator = EvaluationMetrics(y_true, y_pred)
    result = evaluator.evaluate_binary()

    print("Binary Test 1")
    print(result)
    print("Expected confusion matrix: TP=3, FP=1, FN=1, TN=3")
    print()

    # Test 2: model predicts no positive class
    y_true = [1, 0, 1, 0]
    y_pred = [0, 0, 0, 0]

    evaluator = EvaluationMetrics(y_true, y_pred)
    result = evaluator.evaluate_binary()

    print("Binary Test 2 (division-by-zero case for precision)")
    print(result)
    print("Expected precision = 0.0")
    print()

    # Test 3: no positive labels in gold data
    y_true = [0, 0, 0, 0]
    y_pred = [0, 1, 0, 1]

    evaluator = EvaluationMetrics(y_true, y_pred)
    result = evaluator.evaluate_binary()

    print("Binary Test 3 (division-by-zero case for recall)")
    print(result)
    print("Expected recall = 0.0")
    print()

    # Test 4: empty input
    y_true = []
    y_pred = []

    evaluator = EvaluationMetrics(y_true, y_pred)
    result = evaluator.evaluate_binary()

    print("Binary Test 4 (empty lists)")
    print(result)
    print("Expected accuracy = 0.0")
    print()

    print("===== MULTI-CLASS TESTS =====")

    # Test 5: multi-class example
    y_true = ["cat", "dog", "cat", "bird", "dog", "bird", "cat"]
    y_pred = ["cat", "cat", "cat", "bird", "dog", "dog", "bird"]

    evaluator = EvaluationMetrics(y_true, y_pred)
    result = evaluator.evaluate_multiclass()

    print("Multi-class Test 1")
    print(result)
    print()

    # Test 6: integer labels
    y_true = [0, 1, 2, 1, 2, 0, 2]
    y_pred = [0, 2, 2, 1, 0, 0, 1]

    evaluator = EvaluationMetrics(y_true, y_pred)
    result = evaluator.evaluate_multiclass()

    print("Multi-class Test 2")
    print(result)
    print()

    # Test 7: one label never predicted
    y_true = ["A", "B", "C", "A", "B", "C"]
    y_pred = ["A", "A", "A", "A", "B", "B"]

    evaluator = EvaluationMetrics(y_true, y_pred)
    result = evaluator.evaluate_multiclass()

    print("Multi-class Test 3 (some per-label precision/recall edge cases)")
    print(result)
    print()


if __name__ == "__main__":
    run_tests()