# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oDAo7_-wTw2UMpYWYiA_rfA13Ff-zMIv
"""
import csv
import random
import kagglehub
import os

path = kagglehub.dataset_download("uciml/sms-spam-collection-dataset")

#print("Path to dataset files:", path)

path = "/root/.cache/kagglehub/datasets/uciml/sms-spam-collection-dataset/versions/1"

#print(os.listdir(path))

def load_dataset(filename):
  dataset = []
  with open(filename, "r", encoding="latin-1") as file:
    reader = csv.reader(file)

    next (reader) # skip header row

    for row in reader:
      label = row[0]
      text = row[1]

      if label == "ham":
        label = "normal"
      dataset.append((text,label))
  return dataset

dataset = load_dataset("/root/.cache/kagglehub/datasets/uciml/sms-spam-collection-dataset/versions/1"+"/spam.csv")

random.shuffle(dataset)


print(dataset[:5])
print("Dataset size:", len(dataset))

def tokenize(text):
  if isinstance(text, str):
    text = text.lower()
    tokens = text.split()
    return tokens
  else:
    raise TypeError("Expected a string, but received an unexpected type.")

tokenized_dataset = []
for item, label in dataset:
    tokenized_text = tokenize(item)
    tokenized_dataset.append((tokenized_text, label))

print(tokenized_dataset)

total_words = {"spam" : 0, "normal" : 0}
class_counts = {"spam" : 0, "normal" : 0}
word_counts = {"spam" : {}, "normal" : {}}

for item, label in tokenized_dataset:
  class_counts[label] += 1
  for word in item:
    total_words[label] += 1
  for word in set(item):
    word_counts[label][word] = word_counts[label].get(word, 0) + 1

print(word_counts)
print(class_counts)
print(total_words)

priors = {"spam" : 0, "normal" : 0}
for label in priors:
  priors[label] = class_counts[label] / len(tokenized_dataset)
print(priors)

likelihoods = {"spam": {}, "normal": {}}

vocab_size = len(word_counts["spam"]) + len(word_counts["normal"])

for label in likelihoods:
    for word in word_counts[label]:
        likelihoods[label][word] = (word_counts[label][word] + 1) / (total_words[label] + vocab_size)
print(likelihoods)

alpha = 0.1

likelihoods = {"spam": {}, "normal": {}}
vocab_size = len(word_counts["spam"]) + len(word_counts["normal"])
for label in likelihoods:
    for word in word_counts[label]:
        word_count = word_counts[label].get(word, 0)
        likelihoods[label][word] = (word_count + alpha) / (total_words[label] + alpha * vocab_size)

print(likelihoods)

def score(text, label):
  score = priors[label]
  for word in tokenize(text):
    if word in likelihoods[label]:
      score += likelihoods[label][word]
  return score
print(score("free money", "spam"))
print(score("free money", "normal"))

def predict(text):
  score_spam = score(text, "spam")
  score_normal = score(text, "normal")
  if score_spam > score_normal:
    return "spam"
  else:
    return "normal"

print(predict("free money"))
print(predict("let´s meet now"))